{{- $envAll := . }}
{{- range .Values.l2Advertisements }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  labels:
    {{- include "metallb-config.labels" $envAll | nindent 4 }}
spec:
{{- with .interfaces }}
  interfaces:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .ipAddressPools }}
  ipAddressPools:
   {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .ipAddressPoolSelectors }}
  ipAddressPoolSelectors:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .nodeSelectors }}
  nodeSelectors:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
